### ISSUE TITLE
Issue with Training

### ISSUE THREAD

**Issue by sktalha68** [LiuYunlong99/RQ-LLIE#2]
Hello.
I want to ask how to run the training for this model.  The following command you have mentioned uses LOLv1.yml file which does not exist in the repo.

```python
python -m torch.distributed.launch --nproc_per_node 1 --master_port 4320 train.py -opt options/train/LOLv1.yml --launcher pytorch
``` 

when I run options/train/LOLv1/stage1.yml with the above command instead of options/train/LOLv1.yml I get the following error:

```
Traceback (most recent call last):
  File "/media/talha/79e18c32-24dc-4291-918a-8b00897939e13/RQ-LLIE-main/train.py", line 371, in <module>
    main()
  File "/media/talha/79e18c32-24dc-4291-918a-8b00897939e13/RQ-LLIE-main/train.py", line 173, in main
    model.optimize_parameters(current_step)
  File "/media/talha/79e18c32-24dc-4291-918a-8b00897939e13/RQ-LLIE-main/models/model.py", line 123, in optimize_parameters
    output, codebook_loss, _, _ = self.netG(self.real_H)
  File "/home/talha/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/talha/.local/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/talha/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/talha/79e18c32-24dc-4291-918a-8b00897939e13/RQ-LLIE-main/models/arch/network.py", line 165, in forward
    return self.forward_s1(x)
  File "/media/talha/79e18c32-24dc-4291-918a-8b00897939e13/RQ-LLIE-main/models/arch/network.py", line 189, in forward_s1
    x_rec = self.conv_out(f3_d)
  File "/home/talha/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/talha/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/talha/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [3, 64, 3, 3], expected input[2, 256, 32, 32] to have 64 channels, but got 256 channels instead
```  

When I change the conv layer channels from :
```python
self.conv_out = nn.Conv2d(channel_query_dict[curr_res], 3, 3, 1, 1)
```
to this:
```python
 self.conv_out = nn.Conv2d(channel_query_dict[curr_res // 4], 3, 3, 1, 1)
```
in   File "/home/talha/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
    
    
I get the following error:
```
x shape: torch.Size([2, 3, 32, 32])
y shape: torch.Size([2, 3, 128, 128])
Traceback (most recent call last):
  File "/media/talha/79e18c32-24dc-4291-918a-8b00897939e13/RQ-LLIE-main/train.py", line 371, in <module>
    main()
  File "/media/talha/79e18c32-24dc-4291-918a-8b00897939e13/RQ-LLIE-main/train.py", line 173, in main
    model.optimize_parameters(current_step)
  File "/media/talha/79e18c32-24dc-4291-918a-8b00897939e13/RQ-LLIE-main/models/model.py", line 125, in optimize_parameters
    l_pix = self.cri_pix(self.fake_H, self.real_H)
  File "/home/talha/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/talha/79e18c32-24dc-4291-918a-8b00897939e13/RQ-LLIE-main/models/loss.py", line 17, in forward
    diff = x - y
RuntimeError: The size of tensor a (32) must match the size of tensor b (128) at non-singleton dimension 3
```
Can you please help me resolve this issue?

**Comment by LiuYunlong99** [comment]
Thank you for your feedback on this project!
Please change the code `x_rec = self.conv_out(f3_d)` to `x_rec = self.conv_out(f1_d)` in line 187 and code `x_rec = self.conv_out(f3_d)` to `x_rec = self.conv_out(f1_d)` in line 194 of models/arch/network.py.
And we will update the ReadMe file soon.
